# Generated by Django 4.0.4 on 2022-05-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='description',
        ),
        migrations.AddField(
            model_name='feature',
            name='icon_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
