# Generated by Django 4.0.4 on 2022-05-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_telegramuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.CharField(default='4', max_length=255),
        ),
    ]
